# Generated by Django 2.2.9 on 2020-11-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201129_1218'),
        ('posts', '0003_auto_20201129_0929'),
    ]

    operations = [
    ]
