# Generated by Django 2.2.6 on 2021-01-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201229_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Пиши что хочешь и сколько хочешь.Цензура сегодня не для нас.', verbose_name='Текст записи'),
        ),
    ]
